/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */

import '@stencil/core';

declare global {
  namespace JSX {
    interface Element {}
    export interface IntrinsicElements {}
  }
  namespace JSXElements {}

  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;
    componentOnReady(done: (ele?: this) => void): void;

    forceUpdate(): void;
  }

  interface HTMLAttributes {}
}


declare global {

  namespace StencilComponents {
    interface BubbleChannelList {
      'user': string;
    }
  }

  interface HTMLBubbleChannelListElement extends StencilComponents.BubbleChannelList, HTMLStencilElement {}

  var HTMLBubbleChannelListElement: {
    prototype: HTMLBubbleChannelListElement;
    new (): HTMLBubbleChannelListElement;
  };
  interface HTMLElementTagNameMap {
    'bubble-channel-list': HTMLBubbleChannelListElement;
  }
  interface ElementTagNameMap {
    'bubble-channel-list': HTMLBubbleChannelListElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'bubble-channel-list': JSXElements.BubbleChannelListAttributes;
    }
  }
  namespace JSXElements {
    export interface BubbleChannelListAttributes extends HTMLAttributes {
      'user'?: string;
    }
  }
}


declare global {

  namespace StencilComponents {
    interface BubbleChannelSidebar {
      'user': string;
    }
  }

  interface HTMLBubbleChannelSidebarElement extends StencilComponents.BubbleChannelSidebar, HTMLStencilElement {}

  var HTMLBubbleChannelSidebarElement: {
    prototype: HTMLBubbleChannelSidebarElement;
    new (): HTMLBubbleChannelSidebarElement;
  };
  interface HTMLElementTagNameMap {
    'bubble-channel-sidebar': HTMLBubbleChannelSidebarElement;
  }
  interface ElementTagNameMap {
    'bubble-channel-sidebar': HTMLBubbleChannelSidebarElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'bubble-channel-sidebar': JSXElements.BubbleChannelSidebarAttributes;
    }
  }
  namespace JSXElements {
    export interface BubbleChannelSidebarAttributes extends HTMLAttributes {
      'user'?: string;
    }
  }
}


declare global {

  namespace StencilComponents {
    interface BubbleChat {
      'first': string;
      'last': string;
    }
  }

  interface HTMLBubbleChatElement extends StencilComponents.BubbleChat, HTMLStencilElement {}

  var HTMLBubbleChatElement: {
    prototype: HTMLBubbleChatElement;
    new (): HTMLBubbleChatElement;
  };
  interface HTMLElementTagNameMap {
    'bubble-chat': HTMLBubbleChatElement;
  }
  interface ElementTagNameMap {
    'bubble-chat': HTMLBubbleChatElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'bubble-chat': JSXElements.BubbleChatAttributes;
    }
  }
  namespace JSXElements {
    export interface BubbleChatAttributes extends HTMLAttributes {
      'first'?: string;
      'last'?: string;
    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }
